/*
 * twinder
 * CS6650 assignment API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.SwipeDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SwipeApi
 */
@Ignore
public class SwipeApiTest {

    // private final SwipeApi api = new SwipeApi();

    /**
     * 
     *
     * Swipe left or right
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void swipeTest() throws Exception {
//        SwipeDetails body = null;
//        String leftorright = null;
//        api.swipe(body, leftorright);

        // TODO: test validations
        ApiClient apiClient = new ApiClient();
        String LOCAL_URL = "http://localhost:8080/A1_Server_war_exploded";
        String REMOTE_URL = "http://54.212.0.107:8080/A1-Server_war";

        apiClient.setBasePath(LOCAL_URL);
        SwipeApi swipeApi = new SwipeApi(apiClient);
        SwipeDetails body = new SwipeDetails().swipee("21345").swiper("233444").comment("not my type!");
        String leftorright = "left";
        try {
            ApiResponse res = swipeApi.swipeWithHttpInfo(body, leftorright);
            System.out.println(Integer.toString(res.getStatusCode()) + ": " + res.getData());
        } catch (ApiException e) {
            System.out.println(e.getCode() + ": " + e.getResponseBody());
        }


    }
}
